# Generated by Django 6.0.4 on 2026-04-12 19:23

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('description', models.CharField(max_length=255, verbose_name='Sobre mim')),
                ('course', models.CharField(max_length=100, verbose_name='Curso')),
                ('linken', models.CharField(max_length=100, verbose_name='Linken')),
                ('git', models.CharField(max_length=100, verbose_name='Git')),
                ('image_profile_url', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='static/core/images', variations={}, verbose_name='Foto de perfil')),
                ('period', models.CharField(max_length=100, verbose_name='Periodo')),
            ],
        ),
    ]
