# Generated by Django 6.0.4 on 2026-04-12 21:35

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Sobre Mim'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_profile_url',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='static/core/images', variations={}, verbose_name='Foto de Perfil'),
        ),
    ]
