# Generated by Django 6.0.4 on 2026-05-18 20:41

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile_url',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='images/profile/', variations={'thumb': (128, 128)}, verbose_name='Foto de Perfil'),
        ),
    ]
