# Generated by Django 6.0.4 on 2026-06-04 14:40

import django.db.models.deletion
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_image_profile_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil Pessoal', 'verbose_name_plural': 'Perfis Pessois'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linken',
        ),
        migrations.AddField(
            model_name='profile',
            name='linkend',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Linkend'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobre Mim'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Git'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_profile_url',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/profile/', variations={'thumb': (128, 128)}, verbose_name='Foto de Perfil'),
        ),
    ]
