# Generated by Django 6.0.4 on 2026-06-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_options_remove_profile_linken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linkend',
        ),
        migrations.AddField(
            model_name='profile',
            name='linked',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Linked'),
        ),
    ]
