# Generated by Django 6.0.4 on 2026-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_linkend_profile_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Imagem de Perfil'),
        ),
    ]
