# Generated by Django 6.0.4 on 2026-06-05 14:39

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_image_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile_url',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='images/profile/', variations={'thumb': (128, 128)}, verbose_name='Foto de Perfil'),
        ),
    ]
