# Generated by Django 6.0.4 on 2026-06-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_image_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Foto de Perfil'),
        ),
    ]
