# Generated by Django 6.0.4 on 2026-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('PESSOAL', 'Pessoal'), ('DISCIPLINA', 'Disciplina')], default='PESSOAL', max_length=10, verbose_name='Tipo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('git', models.CharField(max_length=100, verbose_name='Git')),
            ],
        ),
    ]
